// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdwvet4gjs7T_BTfbw2nUbo3XV8XRlUE',
    appId: '1:998071319832:web:07354dd830fc2024a6f26d',
    messagingSenderId: '998071319832',
    projectId: 'my-mate-b5aee',
    authDomain: 'my-mate-b5aee.firebaseapp.com',
    storageBucket: 'my-mate-b5aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCls9n1ghCAtWqW8-XQkB6H1nnIIaMRyeg',
    appId: '1:998071319832:ios:c28a6bd7f0f55e2fa6f26d',
    messagingSenderId: '998071319832',
    projectId: 'my-mate-b5aee',
    storageBucket: 'my-mate-b5aee.firebasestorage.app',
    iosBundleId: 'com.example.mymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCls9n1ghCAtWqW8-XQkB6H1nnIIaMRyeg',
    appId: '1:998071319832:ios:c28a6bd7f0f55e2fa6f26d',
    messagingSenderId: '998071319832',
    projectId: 'my-mate-b5aee',
    storageBucket: 'my-mate-b5aee.firebasestorage.app',
    iosBundleId: 'com.example.mymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdwvet4gjs7T_BTfbw2nUbo3XV8XRlUE',
    appId: '1:998071319832:web:aa05ee1873835424a6f26d',
    messagingSenderId: '998071319832',
    projectId: 'my-mate-b5aee',
    authDomain: 'my-mate-b5aee.firebaseapp.com',
    storageBucket: 'my-mate-b5aee.firebasestorage.app',
  );
}
